
name: build workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  mssqldb: ah
  postgresqldb: ah
  mssqlpassword: sysadmin@1234
  postgreqlpassword: postgres
  azuresqlsecret: ${{ secrets.AzureSqlSecret }}
  mssqlsecret: "Server=localhost,1433;Initial Catalog=ah;Persist Security Info=False;User ID=sa;Password=sysadmin@1234;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=true;Connection Timeout=30;"
  postgresqlsecret: "host=localhost;port=5432;username=postgres;password=postgres;database=ah"

jobs:
  
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    
    - name: install net8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: restore
      run: dotnet restore

    - name: build
      run: dotnet build --no-restore

  test:
    if: ${{ success() }}
    needs: build
    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server
        ports:
          - 1433:1433
        env:
          ACCEPT_EULA: true
          MSSQL_SA_PASSWORD: ${{ env.mssqlpassword }}

      postgres:
        image: postgres
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: ${{ env.postgresqldb }}
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ env.postgreqlpassword }}

    steps:
    - name: checkout repo
      uses: actions/checkout@v4

    - name: run scripts
      run: ./scripts.sh

    - name: test
      run: |
        dotnet build
        dotnet test --no-build --verbosity normal

    
