name: packs worklfow

on:
  push:
    tags:
      - '*.*.*'

env:
  packageIdd: AsyncHandler.EventSourcing

jobs:
  pack:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    defaults:
      run:
        working-directory: ./src

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
      
    - name: Install net8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: build
      run: dotnet build --configuration release

    - id: get-version
      run: |
        vtag=${{ github.ref_name }}; tag=${vtag#v}; echo "tag=$tag" >> $GITHUB_OUTPUT

    - name: pack
      run: >
        dotnet pack --no-build --no-restore --configuration release -p:PackageId=${{ env.packageIdd }}
        -p:PackageVersion=${{ steps.get-version.outputs.tag }} --output .

    - name: authenticate
      run: >
        dotnet nuget add source --username asynchandler --password ${{ secrets.GITHUB_TOKEN }}
        --store-password-in-clear-text --name workflow "https://nuget.pkg.github.com/asynchandler/index.json"

    - name: push
      run: >
        dotnet nuget push ${{ env.packageIdd }}.${{ steps.get-version.outputs.tag }}.nupkg
        -k ${{ secrets.GITHUB_TOKEN }} -s workflow
